include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/assets/gen**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
  errors:
    invalid_annotation_target: ignore